### ISSUE TITLE
No module?

### ISSUE THREAD

**Issue by Zibri** [mstr-/twp-ggdump#2]
For some reason after pip install I get

/usr/bin/python: No module named ggdump

**Comment by Zibri** [comment]
but if I do: pip3 install then python3 -m ggdump works.

**Comment by Zibri** [comment]
Anyway, extracting the linux version ggpack1 I get a few skipped file saying "SKIPPED: (missing offset or size)"

**Comment by mstr-** [comment]
Thanks for your comment. GGDump is made for python3. I'll update the instructions. There is no fix for skipped files yet.
